<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="CHAKRI" failures="1" tests="3" name="com.framework.runners.TestRunner" time="20.793" errors="0" timestamp="2025-09-15T18:13:59 IST" skipped="2">
  <testcase classname="com.framework.runners.TestRunner" name="runScenario" time="6.031">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at com.framework.stepdefinitions.LoginSteps.user_logs_in_with_excel_sheet(LoginSteps.java:40)
at âœ½.user logs in with excel sheet tomsmith and SuperSecretPassword!(file:///C:/Users/Chakr/Downloads/selenium-hybrid-framework/src/test/resources/features/login.feature:7)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="com.framework.runners.TestRunner" name="runScenario" time="6.694">
    <skipped/>
  </testcase> <!-- runScenario -->
  <testcase classname="com.framework.runners.TestRunner" name="runScenario" time="8.068">
    <skipped/>
  </testcase> <!-- runScenario -->
</testsuite> <!-- com.framework.runners.TestRunner -->
